image: docker:latest

stages:
  - basic-platform
  - other-platforms

before_script:
  - docker info
  - docker images

.default:
  script:
    - docker build -t hw-testenv --build-arg BASE_IMAGE=$BASE_IMAGE --build-arg NAME=$NAME --target build -f docker/helloenv .
    - docker run hw-testenv ./hello.sh testing

debian-stable-job:
  stage: basic-platform
  extends: .default
  variables:
    BASE_IMAGE: baagaard/hw-debian-stable
    NAME: custom-debian-stable

debian-testing-job:
  stage: other-platforms
  extends: .default
  variables:
    BASE_IMAGE: baagaard/hw-debian-testing
    NAME: custom-debian-testing

ubuntu-18.04-job:
  stage: other-platforms
  extends: .default
  variables:
    BASE_IMAGE: baagaard/hw-ubuntu-18.04
    NAME: custom-ubuntu-18.04
