image: debian:stable

stages:
  - basic-platform
  - other-platforms

before_script:
  - echo "Before script section"

after_script:
  - echo "After script section"

debian-stable-job:
  stage: basic-platform
  image: hw-debian-stable
  script:
    - echo "Starting job"
    - echo "$MYCONFIG"
    - ./hello.sh basic

debian-testing-job:
  stage: other-platforms
  image: hw-debian-testing
  script:
    - echo "Starting another job"
    - echo "$MYCONFIG"
    - ./hello.sh other-1
