image: docker:latest

stages:
  - manual-trigger
  - basic-platform
  - other-platforms
  - auto-documentation

.pull-request:
  only:
    - external_pull_requests

.builder:
  #tags:
  #  - arling
  extends: .pull-request
  stage: other-platforms
  script:
    - docker build -t hw-testenv --build-arg BASE_IMAGE=$BASE_IMAGE --build-arg NAME=$NAME --target build -f docker/helloenv .
    - docker run hw-testenv ./hello.sh testing

.builder-first:
  extends: .builder
  stage: basic-platform

.doc:
  when: manual
  script:
    - docker run hw-testenv ./hello.sh $NAME

trigger-job:
  stage: manual-trigger
  when: manual
  extends: .pull-request
  allow_failure: false
  script:
    - echo "Pipeline triggered manually"

debian-stable-job:
  extends: .builder-first
  variables:
    BASE_IMAGE: baagaard/hw-debian-stable
    NAME: custom-debian-stable

debian-testing-job:
  extends: .builder
  variables:
    BASE_IMAGE: baagaard/hw-debian-testing
    NAME: custom-debian-testing

ubuntu-18.04-job:
  extends: .builder
  variables:
    BASE_IMAGE: baagaard/hw-ubuntu-18.04
    NAME: custom-ubuntu-18.04

auto-doc-job:
  stage: auto-documentation
  extends:
    - .pull-request
    - .doc
  variables:
    BASE_IMAGE: baagaard/hw-debian-stable
    NAME: auto-documentation

manual-doc-job:
  stage: basic-platform
  extends: .doc
  only:
    - main
  variables:
    BASE_IMAGE: baagaard/hw-debian-stable
    NAME: manual-documentation
